"""Regenerate every derived artefact from the raw per-setting CSVs.

The single entry point for reproducibility: it runs the analysis scripts in
dependency order (raw run CSVs + the official reference table -> derived tables
-> figures are regenerated by the figure scripts separately). Every script is
pure: it reads `results/run_csv/*.csv` and `results/reference/
official_per_setting.csv`, and writes into `results/analysis/`.

Usage (repository root, harness python not required - these are pandas scripts):
    python code/analysis/regenerate_all.py            # analysis tables
    python code/analysis/regenerate_all.py --figures  # + figure PDF/SVG/PNG/TIFF

Exit code is non-zero if any step fails, and the failing script is printed.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ANA = ROOT / "code" / "analysis"
# release layout keeps the scripts in paper/figures; the development worktree
# keeps them in figures/ at the repository root - accept either.
FIGS = next((p for p in (ROOT / "paper" / "figures", ROOT / "figures") if p.is_dir()),
            ROOT / "paper" / "figures")

# Ordered: tables that other tables read come first.
ANALYSIS_STEPS = [
    # core tables
    "build_tables.py",
    # shift slices and their statistics
    "generalization_by_cm.py",
    "generalization_seeds.py",
    "generalization_by_band.py",
    "generalization_432_summary.py",
    "acd_three_seeds.py",
    "stats_hardening.py",
    "robust_seed44.py",
    # extended slice tables (added 2026-09-18)
    "generalization_432_extended.py",
    "slice_summary_extended.py",
    # mechanism interventions
    "pole_offset_analysis.py",
    "pole_intervention_analysis.py",
    "pole_snap_seeds.py",
    "pole_snap_horizon.py",
    "pole_shift_ladder.py",
    "shift_snap_analysis.py",
    "pole_snap_capacity.py",
    # capacity / data scaling / variants
    "capacity_curve.py",
    "data_frac_curve.py",
    "variant_family_comparison.py",
    # baselines and ladders
    "classical_ladder_extend.py",
    "baseline_zoo.py",
]

FIGURE_STEPS = [
    "make_fig_pole.py",
    "make_fig_anatomy.py",
    "make_fig_condition.py",
    "make_fig_mobility.py",
    "make_fig_pareto.py",
    "make_fig_shift_acd.py",
    "make_fig_pole_gain.py",
    "make_fig_snap_slices.py",
    "flatten_rasters.py",
]


def run(script: Path, cwd: Path) -> bool:
    t0 = time.time()
    proc = subprocess.run([sys.executable, str(script)], cwd=str(cwd),
                          capture_output=True, text=True)
    ok = proc.returncode == 0
    skip = ok and "[skip]" in (proc.stdout or "")
    tag = "skip" if skip else ("ok " if ok else "FAIL")
    print(f"[{tag}] {script.name} ({time.time() - t0:.1f}s)")
    if skip:
        for line in (proc.stdout or "").splitlines():
            if "[skip]" in line:
                print(f"       {line.strip()}")
    if not ok:
        tail = (proc.stderr or proc.stdout or "").strip().splitlines()[-6:]
        for line in tail:
            print(f"       {line}")
    return ok


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--figures", action="store_true",
                    help="also rebuild the eight publication figures")
    args = ap.parse_args()

    failures: list[str] = []
    for name in ANALYSIS_STEPS:
        path = ANA / name
        if not path.exists():
            print(f"[skip] {name} (not present)")
            continue
        if not run(path, ROOT):
            failures.append(name)

    if args.figures:
        for name in FIGURE_STEPS:
            path = FIGS / name
            if not path.exists():
                print(f"[skip] {name} (not present)")
                continue
            if not run(path, ROOT):
                failures.append(name)

    print()
    if failures:
        print(f"{len(failures)} step(s) failed: {failures}")
        return 1
    print("all requested artefacts regenerated successfully")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
